### ISSUE TITLE
Vite doesn't work with solid 1.0.0-rc.3

### ISSUE THREAD

**Issue by maksimil** [solidjs/vite-plugin-solid#14]
On build `vite` errors out with this error:

```
> node_modules/.pnpm/vite@2.3.7/node_modules/vite/dist/node/chunks/dep-bc228bbb.js:32122:7: error: [plugin: vite:dep-scan] Missing "./dev" export in "solid-js" package
    32122 │   throw new Error(
          ╵         ^
    at bail (D:\Projects\NodeJS\solid-ssr-att\node_modules\.pnpm\vite@2.3.7\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:32122:8)
    at resolve$1 (D:\Projects\NodeJS\solid-ssr-att\node_modules\.pnpm\vite@2.3.7\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:32198:10)
    at resolveExports (D:\Projects\NodeJS\solid-ssr-att\node_modules\.pnpm\vite@2.3.7\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:32627:12)
    at resolveDeepImport (D:\Projects\NodeJS\solid-ssr-att\node_modules\.pnpm\vite@2.3.7\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:32644:26)
    at tryNodeResolve (D:\Projects\NodeJS\solid-ssr-att\node_modules\.pnpm\vite@2.3.7\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:32433:11)
    at Context.resolveId (D:\Projects\NodeJS\solid-ssr-att\node_modules\.pnpm\vite@2.3.7\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:32317:28)
    at Object.resolveId (D:\Projects\NodeJS\solid-ssr-att\node_modules\.pnpm\vite@2.3.7\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:44708:55)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Context.resolve (D:\Projects\NodeJS\solid-ssr-att\node_modules\.pnpm\vite@2.3.7\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:44510:23)
    at async Object.resolveId (D:\Projects\NodeJS\solid-ssr-att\node_modules\.pnpm\vite@2.3.7\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:44708:32)

   node_modules/.pnpm/vite@2.3.7/node_modules/vite/dist/node/chunks/dep-bc228bbb.js:45002:18: note: This error came from the "onResolve" callback registered here
    45002 │             build.onResolve({
          ╵                   ~~~~~~~~~
    at setup (D:\Projects\NodeJS\solid-ssr-att\node_modules\.pnpm\vite@2.3.7\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:45002:19)
    at handlePlugins (D:\Projects\NodeJS\solid-ssr-att\node_modules\.pnpm\esbuild@0.12.8\node_modules\esbuild\lib\main.js:736:23)
    at Object.buildOrServe (D:\Projects\NodeJS\solid-ssr-att\node_modules\.pnpm\esbuild@0.12.8\node_modules\esbuild\lib\main.js:1024:7)
    at D:\Projects\NodeJS\solid-ssr-att\node_modules\.pnpm\esbuild@0.12.8\node_modules\esbuild\lib\main.js:1748:17
    at new Promise (<anonymous>)
    at Object.build (D:\Projects\NodeJS\solid-ssr-att\node_modules\.pnpm\esbuild@0.12.8\node_modules\esbuild\lib\main.js:1747:14)
    at Object.build (D:\Projects\NodeJS\solid-ssr-att\node_modules\.pnpm\esbuild@0.12.8\node_modules\esbuild\lib\main.js:1623:51)
    at D:\Projects\NodeJS\solid-ssr-att\node_modules\.pnpm\vite@2.3.7\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:44865:54
    at Array.map (<anonymous>)

   src/App.tsx:1:39: note: The plugin "vite:dep-scan" was triggered by this import
        1 │ import { Component, createState } from "solid-js";
          ╵                                        ~~~~~~~~~~

[31merror when starting dev server:[39m
[31mError: Build failed with 1 error:[39m
[31mnode_modules/.pnpm/vite@2.3.7/node_modules/vite/dist/node/chunks/dep-bc228bbb.js:32122:7: error: [plugin: vite:dep-scan] Missing "./dev" export in "solid-js" package[39m
[31m    at failureErrorWithLog (D:\Projects\NodeJS\solid-ssr-att\node_modules\.pnpm\esbuild@0.12.8\node_modules\esbuild\lib\main.js:1449:15)[39m
[31m    at D:\Projects\NodeJS\solid-ssr-att\node_modules\.pnpm\esbuild@0.12.8\node_modules\esbuild\lib\main.js:1131:28[39m
[31m    at runOnEndCallbacks (D:\Projects\NodeJS\solid-ssr-att\node_modules\.pnpm\esbuild@0.12.8\node_modules\esbuild\lib\main.js:921:63)[39m
[31m    at buildResponseToResult (D:\Projects\NodeJS\solid-ssr-att\node_modules\.pnpm\esbuild@0.12.8\node_modules\esbuild\lib\main.js:1129:7)[39m
[31m    at D:\Projects\NodeJS\solid-ssr-att\node_modules\.pnpm\esbuild@0.12.8\node_modules\esbuild\lib\main.js:1236:14[39m
[31m    at D:\Projects\NodeJS\solid-ssr-att\node_modules\.pnpm\esbuild@0.12.8\node_modules\esbuild\lib\main.js:609:9[39m
[31m    at handleIncomingPacket (D:\Projects\NodeJS\solid-ssr-att\node_modules\.pnpm\esbuild@0.12.8\node_modules\esbuild\lib\main.js:706:9)[39m
[31m    at Socket.readFromStdout (D:\Projects\NodeJS\solid-ssr-att\node_modules\.pnpm\esbuild@0.12.8\node_modules\esbuild\lib\main.js:576:7)[39m
[31m    at Socket.emit (events.js:315:20)[39m
[31m    at addChunk (_stream_readable.js:309:12)[39m
```

**Comment by maksimil** [comment]
Updated to `vite-plugin-solid@2.0.0-rc.2` and everything worked. Thanks for adding a note about it in the readme!
